# Generated by Django 4.2.4 on 2023-11-16 11:36

import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_userprofile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name': 'guruh ',
                'verbose_name_plural': 'Guruh',
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'kurs ', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'foydalanuvchi ', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(default='-', max_length=255, verbose_name='manzil'),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.course', verbose_name='kurs'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name="qo'shilgan sanasi"),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='elektron pochta manzili'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Ushbu foydalanuvchini faol deb hisoblash kerakligini belgilaydi.Hisoblarni o'chirish o'rniga bu belgini olib tashlang.", verbose_name='Talaba status'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Foydalanuvchining ushbu administrator saytiga kirishi mumkinligini belgilaydi.', verbose_name='Xodim statusi'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Familiya'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharif'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(error_messages={'unique': 'Bunday foydalanuvchi nomiga ega foydalanuvchi allaqachon mavjud.'}, help_text='Majburiy. 150 yoki undan kam belgi. Faqat harflar, raqamlar va @/./+/-/_.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='Foydalanuvchi nomi'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.group', verbose_name='kurs'),
        ),
    ]
