# Generated by Django 4.2.4 on 2023-11-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Sharif')),
                ('address', models.CharField(default='-', max_length=255, verbose_name='manzil')),
                ('user_type', models.CharField(choices=[("o'qituvchi", "O'qituvchi"), ('talaba', 'Talaba'), ('xodim', 'Xodim'), ('boshqa', 'Boshqa')], default='talaba', max_length=255, verbose_name='lavozim')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.course', verbose_name='kurs')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.group', verbose_name='guruh')),
            ],
            options={
                'verbose_name': 'foydalanuvchi ',
                'verbose_name_plural': 'Foydalanuvchilar',
            },
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
