# Generated by Django 4.2.4 on 2023-11-27 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_delete_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.course', verbose_name='kurs'),
        ),
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ForeignKey(blank=True, default='-', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='users.group', verbose_name='guruh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, default='-', max_length=255, null=True, verbose_name='Sharif'),
        ),
    ]
