# Generated by Django 4.2.4 on 2023-11-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alphabet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name': 'alifbo ',
                'verbose_name_plural': 'Alifbolar',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name': 'kategoriya ',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name': 'til ',
                'verbose_name_plural': 'Tillar',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('description', models.TextField(verbose_name="ta'rif")),
                ('author', models.CharField(max_length=255, verbose_name='muallif')),
                ('publication', models.CharField(max_length=255, verbose_name='nashriyot')),
                ('publication_date', models.DateField(verbose_name='nashr sanasi')),
                ('amount', models.IntegerField(default=0, verbose_name='miqdori')),
                ('code_number', models.IntegerField(blank=True, null=True, verbose_name='kitob raqami')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan sanasi")),
                ('alphabet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphabet', to='books.alphabet', verbose_name='alifbo')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='books.category', verbose_name='kategoriya')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='books.language', verbose_name='til')),
            ],
            options={
                'verbose_name': 'kitob ',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-amount'],
            },
        ),
    ]
