# Generated by Django 4.2.4 on 2023-11-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='language',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='nomi'),
        ),
    ]
