# Generated by Django 4.2.4 on 2023-11-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_language_slug_alter_language_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alphabet',
            options={'verbose_name_plural': 'Alifbolar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Tillar'},
        ),
        migrations.AlterField(
            model_name='alphabet',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='alphabet',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='nomi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=255, unique=True, verbose_name='nomi'),
        ),
    ]
