# Generated by Django 4.2.4 on 2023-11-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_alphabet_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterField(
            model_name='book',
            name='alphabet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alphabet', to='books.alphabet', verbose_name='alifbo'),
        ),
        migrations.AlterField(
            model_name='book',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='miqdori'),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=255, verbose_name='muallif'),
        ),
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='books.category', verbose_name='kategoriya'),
        ),
        migrations.AlterField(
            model_name='book',
            name='code_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='kitob raqami'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan sanasi:"),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name="ta'rif"),
        ),
        migrations.AlterField(
            model_name='book',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='language', to='books.language', verbose_name='til'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication',
            field=models.CharField(max_length=255, verbose_name='nashriyot'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(verbose_name='nashr sanasi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=255, verbose_name='nomi'),
        ),
        migrations.DeleteModel(
            name='E_Book',
        ),
        migrations.DeleteModel(
            name='E_Category',
        ),
    ]
