# Generated by Django 4.2.4 on 2023-11-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_options_alter_book_alphabet_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alphabet',
            options={'verbose_name': 'alifbo ', 'verbose_name_plural': 'Alifbolar'},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'kitob ', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'kategoriya ', 'verbose_name_plural': 'Kategoriyalar'},
        ),
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name': 'til ', 'verbose_name_plural': 'Tillar'},
        ),
    ]
