# Generated by Django 4.2.4 on 2023-11-16 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_alphabet_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-amount'], 'verbose_name': 'kitob ', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterField(
            model_name='book',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan sanasi"),
        ),
    ]
