# Generated by Django 4.2.4 on 2023-11-18 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_options_alter_book_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='code_number',
        ),
        migrations.AddField(
            model_name='book',
            name='location_book',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='kitob joylashuvi'),
        ),
        migrations.AddField(
            model_name='book',
            name='number_inv',
            field=models.IntegerField(blank=True, null=True, verbose_name='INV raqami'),
        ),
        migrations.AddField(
            model_name='book',
            name='number_isbn',
            field=models.IntegerField(blank=True, null=True, verbose_name='ISBN raqami'),
        ),
        migrations.AddField(
            model_name='book',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='kitob narxi'),
        ),
    ]
