# Generated by Django 4.2.4 on 2023-11-16 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='E_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True, verbose_name='nomi')),
                ('slug', models.SlugField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Kategoriyasi',
            },
        ),
        migrations.CreateModel(
            name='E_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='nomi')),
                ('file', models.FileField(upload_to='files/%y%m%d', verbose_name='fayl')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name="qo'shilgan sana")),
                ('size', models.FloatField(blank=True, default=0, editable=False, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_category', to='e_books.e_category', verbose_name='kategoriya')),
            ],
            options={
                'verbose_name_plural': 'Kitoblar',
            },
        ),
    ]
