# Generated by Django 4.2.4 on 2023-11-16 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('e_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='e_book',
            options={'verbose_name': 'kitob ', 'verbose_name_plural': 'Kitoblar'},
        ),
        migrations.AlterModelOptions(
            name='e_category',
            options={'verbose_name': 'kategoriya ', 'verbose_name_plural': 'Kategoriyasi'},
        ),
    ]
