# Generated by Django 4.2.4 on 2023-11-16 19:53

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('topshirilgan', 'Topshirilgan'), ('topshirilmagan', 'Topshirilmagan')], default='topshirilmagan', max_length=255, verbose_name='status')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='berilgan sana')),
                ('return_date', models.DateTimeField(blank=True, null=True, verbose_name='qaytarilgan sana')),
                ('book', models.ForeignKey(error_messages={'invalid': 'Bu kitobdan kutubxonada qolmagan.'}, limit_choices_to={'amount__gt': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='book_orders', to='books.book', validators=[orders.models.book_validator], verbose_name='kitob')),
            ],
            options={
                'verbose_name': 'kitob berish ',
                'verbose_name_plural': 'Kitob Berish',
            },
        ),
    ]
