# Generated by Django 4.2.4 on 2023-11-16 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0005_alter_alphabet_options_alter_book_options_and_more'),
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'kitob berish ', 'verbose_name_plural': 'Kitob Berish'},
        ),
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='book_orders', to='books.book', verbose_name='kitob'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='berilgan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='qaytarilgan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('topshirilgan', 'Topshirilgan'), ('topshirilmagan', 'Topshirilmagan')], default='topshirilmagan', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to=settings.AUTH_USER_MODEL, verbose_name='foydalanuvchi'),
        ),
    ]
