# Generated by Django 4.2.4 on 2023-11-16 11:36

from django.db import migrations, models
import django.db.models.deletion
import orders.models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_alter_book_options_alter_book_created_date'),
        ('orders', '0003_alter_order_options_alter_order_book_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='book',
            field=models.ForeignKey(error_messages={'invalid': 'Bu kitobdan kutubxonada qolmagan.'}, limit_choices_to={'amount__gt': 0}, on_delete=django.db.models.deletion.PROTECT, related_name='book_orders', to='books.book', validators=[orders.models.book_validator], verbose_name='kitob'),
        ),
    ]
