# Generated by Django 4.2.4 on 2023-11-18 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='berilgan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='qaytarish sana'),
        ),
    ]
