# Generated by Django 4.2.4 on 2023-11-18 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_delete_userprofile'),
        ('orders', '0005_alter_order_created_date_alter_order_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_orders', to='users.user', verbose_name='foydalanuvchi'),
        ),
    ]
