# Generated by Django 4.2.4 on 2023-11-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_book_location_book'),
        ('orders', '0006_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='book',
        ),
        migrations.AddField(
            model_name='order',
            name='books',
            field=models.ManyToManyField(error_messages={'invalid': 'Bu kitobdan kutubxonada qolmagan.'}, limit_choices_to={'amount__gt': 0}, related_name='book_orders', to='books.book', verbose_name='kitob'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_date',
            field=models.DateField(blank=True, null=True, verbose_name='berilgan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='qaytarish sana'),
        ),
    ]
